### PR TITLE
Use Date-Formatter on ObjectMapper and expose as Bean

### PR DESCRIPTION
**Pull request by jbellmann**

### CODE REVIEW

**Comment by jbellmann** [comment]
has to be cleaned up, do we have some tests to check it works?

**Comment by lasomethingsomething** [comment]
@rwitzel @jbellmann Did you guys discuss what to do here next?

**Comment by Raffo** [comment]
Can we do something for this PR? It has been pending for some time.

**Comment by lasomethingsomething** [comment]
As @Raffo notes, this PR has been sitting for a while. @rwitzel @jbellmann, this was your original work -- how would you like to resolve?

**Comment by rwitzel** [comment]
:+1:

**Pull request closed without merging**
