### PR TITLE
Fix issues reported by IntelliJ IDEA

### PR DESCRIPTION
**Pull request by semonte**
- Optimized imports
- Removed unnecessary type declarations when using generics
- Replaced statement lambdas with expression lambdas when possible
- Simplified for loops (use for each loops when possible)
- Removed unused variables
- Removed redundant variable initializations
- Simplified if else statements
- Removed unnecessary null checking
- Use Java 8 stream API when possible
- Fixed Optional.ofNullable() calls. There were many calls like
  Optional.ofNullable(null), changed them to Optional.empty().

### CODE REVIEW

**Comment by semonte** [comment]
Coverage seems to fall a bit because I have removed code that was included in code coverage before.

**Comment by semonte** [comment]
I will write a test for LanguageStats class, it is actually not covered at all by any tests.

**Comment by danpersa** [comment]
lgtm -> why is this not merged yet?

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
